"""
This type stub file was generated by pyright.
"""

from qdarktheme.qtpy.qt_compat import QT_API, qt_import_error
from PySide6.QtCore import *
from PyQt6.QtCore import *

"""Module for QtCore."""
if QT_API is None:
    ...
if QT_API == "PySide6":
    ...
else:
    Slot = ...
    Signal = ...
