"""
This type stub file was generated by pyright.
"""

_current_user_directory = ...

class FileDialog:
    @staticmethod
    def getSaveFileName(
        parent=..., title=..., file_dir=..., ext_filter=...
    ):  # -> Tuple[str, str]:
        ...

    @staticmethod
    def getOpenFileName(
        parent=..., title=..., file_dir=..., ext_filter=...
    ):  # -> Tuple[str, str]:
        ...

class BaseDialog:
    @staticmethod
    def message_dialog(
        parent=..., text=..., title=..., dialog_icon=..., custom_icon=...
    ):  # -> None:
        ...

    @staticmethod
    def question_dialog(
        parent=..., text=..., title=..., dialog_icon=..., custom_icon=...
    ):  # -> bool:
        ...
