"""
This type stub file was generated by pyright.
"""

from qtpy import QtWidgets

class _NodeGroupBox(QtWidgets.QGroupBox):
    def __init__(self, label, parent=...) -> None: ...
    def setTitle(self, text):  # -> None:
        ...

    def setTitleAlign(self, align=...):  # -> None:
        ...

    def add_node_widget(self, widget):  # -> None:
        ...

    def get_node_widget(self):  # -> QWidget:
        ...

class NodeBaseWidget(QtWidgets.QGraphicsProxyWidget):
    """
    This is the main wrapper class that allows a ``QtWidgets.QWidget`` to be
    added in a :class:`NodeGraphQt.BaseNode` object.

    .. inheritance-diagram:: NodeGraphQt.NodeBaseWidget
        :parts: 1

    Args:
        parent (NodeGraphQt.BaseNode.view): parent node view.
        name (str): property name for the parent node.
        label (str): label text above the embedded widget.
    """

    value_changed = ...
    def __init__(self, parent=..., name=..., label=...) -> None: ...
    def setToolTip(self, tooltip):  # -> None:
        ...

    def on_value_changed(self, *args, **kwargs):  # -> None:
        """
        This is the slot function that
        Emits the widgets current :meth:`NodeBaseWidget.value` with the
        :attr:`NodeBaseWidget.value_changed` signal.

        Args:
            args: not used.
            kwargs: not used.

        Emits:
            str, object: <node_property_name>, <node_property_value>
        """
        ...

    @property
    def type_(self):  # -> str:
        """
        Returns the node widget type.

        Returns:
            str: widget type.
        """
        ...

    @property
    def node(self):  # -> None:
        """
        Returns the node object this widget is embedded in.
        (This will return ``None`` if the widget has not been added to
        the node yet.)

        Returns:
            NodeGraphQt.BaseNode: parent node.
        """
        ...

    def get_icon(self, name):  # -> QIcon:
        """
        Returns the default icon from the Qt framework.

        Returns:
            str: icon name.
        """
        ...

    def get_name(self):  # -> None:
        """
        Returns the parent node property name.

        Returns:
            str: property name.
        """
        ...

    def set_name(self, name):  # -> None:
        """
        Set the property name for the parent node.

        Important:
            The property name must be set before the widget is added to
            the node.

        Args:
            name (str): property name.
        """
        ...

    def get_value(self):
        """
        Returns the widgets current value.

        You must re-implement this property to if you're using a custom widget.

        Returns:
            str: current property value.
        """
        ...

    def set_value(self, text):
        """
        Sets the widgets current value.

        You must re-implement this property to if you're using a custom widget.

        Args:
            text (str): new text value.
        """
        ...

    def get_custom_widget(self):
        """
        Returns the embedded QWidget used in the node.

        Returns:
            QtWidgets.QWidget: nested QWidget
        """
        ...

    def set_custom_widget(self, widget):  # -> None:
        """
        Set the custom QWidget used in the node.

        Args:
            widget (QtWidgets.QWidget): custom.
        """
        ...

    def get_label(self):  # -> str:
        """
        Returns the label text displayed above the embedded node widget.

        Returns:
            str: label text.
        """
        ...

    def set_label(self, label=...):  # -> None:
        """
        Sets the label text above the embedded widget.

        Args:
            label (str): new label ext.
        """
        ...

class NodeComboBox(NodeBaseWidget):
    """
    Displays as a ``QComboBox`` in a node.

    .. inheritance-diagram:: NodeGraphQt.widgets.node_widgets.NodeComboBox
        :parts: 1

    .. note::
        `To embed a` ``QComboBox`` `in a node see func:`
        :meth:`NodeGraphQt.BaseNode.add_combo_menu`
    """

    def __init__(self, parent=..., name=..., label=..., items=...) -> None: ...
    @property
    def type_(self):  # -> Literal['ComboNodeWidget']:
        ...

    def get_value(self):  # -> str:
        """
        Returns the widget current text.

        Returns:
            str: current text.
        """
        ...

    def set_value(self, text=...):  # -> None:
        ...

    def add_item(self, item):  # -> None:
        ...

    def add_items(self, items=...):  # -> None:
        ...

    def all_items(self):  # -> list[Any]:
        ...

    def sort_items(self, reversed=...):  # -> None:
        ...

    def clear(self):  # -> None:
        ...

class NodeLineEdit(NodeBaseWidget):
    """
    Displays as a ``QLineEdit`` in a node.

    .. inheritance-diagram:: NodeGraphQt.widgets.node_widgets.NodeLineEdit
        :parts: 1

    .. note::
        `To embed a` ``QLineEdit`` `in a node see func:`
        :meth:`NodeGraphQt.BaseNode.add_text_input`
    """

    def __init__(
        self, parent=..., name=..., label=..., text=..., placeholder_text=...
    ) -> None: ...
    @property
    def type_(self):  # -> Literal['LineEditNodeWidget']:
        ...

    def get_value(self):  # -> str:
        """
        Returns the widgets current text.

        Returns:
            str: current text.
        """
        ...

    def set_value(self, text=...):  # -> None:
        """
        Sets the widgets current text.

        Args:
            text (str): new text.
        """
        ...

class NodeCheckBox(NodeBaseWidget):
    """
    Displays as a ``QCheckBox`` in a node.

    .. inheritance-diagram:: NodeGraphQt.widgets.node_widgets.NodeCheckBox
        :parts: 1

    .. note::
        `To embed a` ``QCheckBox`` `in a node see func:`
        :meth:`NodeGraphQt.BaseNode.add_checkbox`
    """

    def __init__(
        self, parent=..., name=..., label=..., text=..., state=...
    ) -> None: ...
    @property
    def type_(self):  # -> Literal['CheckboxNodeWidget']:
        ...

    def get_value(self):
        """
        Returns the widget checked state.

        Returns:
            bool: checked state.
        """
        ...

    def set_value(self, state=...):  # -> None:
        """
        Sets the widget checked state.

        Args:
            state (bool): check state.
        """
        ...
