"""
This type stub file was generated by pyright.
"""

from typing import Set, Type
from .gs import GsClient
from .hf import hf_get_from_cache
from .http import HttpClient
from .r2 import R2Client
from .s3 import S3Client
from .scheme_client import SchemeClient
from .beaker import BeakerClient

__all__ = [
    "GsClient",
    "HttpClient",
    "S3Client",
    "R2Client",
    "SchemeClient",
    "hf_get_from_cache",
]
_SCHEME_TO_CLIENT = ...

def add_scheme_client(client: Type[SchemeClient]) -> None:
    """
    Add a new :class:`SchemeClient`.

    This can be used to extend :func:`cached_path.cached_path()` to handle custom schemes, or handle
    existing schemes differently.
    """
    ...

if BeakerClient is not None:
    ...

def get_scheme_client(resource: str) -> SchemeClient:
    """
    Get the right client for the given resource.
    """
    ...

def get_supported_schemes() -> Set[str]:
    """
    Return all supported URL schemes.
    """
    ...
