"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional
from ..common import PathOrStr

"""
HuggingFace Hub.

Unlike the other schemes, we don't implement a `SchemeClient` subclass here because
`huggingface_hub` handles the caching logic internally in essentially the same way.
"""

def hf_hub_download(
    model_identifier: str, filename: Optional[str], cache_dir: Optional[PathOrStr] = ...
) -> Path: ...
def hf_get_from_cache(url: str, cache_dir: Optional[PathOrStr] = ...) -> Path: ...
