"""
This type stub file was generated by pyright.
"""

from qdarktheme.qtpy.qt_compat import QtImportError
from qdarktheme.qtpy.qt_version import __version__
from qdarktheme.qtpy import QtCore, QtGui, QtSvg, QtWidgets

"""Package applying Qt compat of PyQt6, PySide6, PyQt5 and PySide2."""
