"""
This type stub file was generated by pyright.
"""

from qdarktheme.qtpy.QtGui import QIcon
from qdarktheme.qtpy.QtWidgets import QProxyStyle, QStyle, QStyleOption

class QDarkThemeStyle(QProxyStyle):
    """Style proxy to improve theme."""

    def __init__(self) -> None:
        """Initialize style proxy."""
        ...

    def standardIcon(
        self, standard_icon: QStyle.StandardPixmap, option: QStyleOption | None, widget
    ) -> QIcon:
        """Implement QProxyStyle.standardIcon."""
        ...
