"""
This type stub file was generated by pyright.
"""

import logging
from pathlib import Path

"""Utility methods for qdarktheme."""
_OPERATORS = ...

def multi_replace(target: str, replacements: dict[str, str]) -> str:
    """Given a string and a replacement map, it returns the replaced string.

    See https://gist.github.com/bgusach/a967e0587d6e01e889fd1d776c5f3729.

    Args:
        target: String to execute replacements on.
        replacements: Replacement dictionary {value to find: value to replace}.

    Returns:
        str: Target string that replaced with `replacements`.
    """
    ...

def get_logger(logger_name: str) -> logging.Logger:
    """Return the logger with the name specified by logger_name arg.

    Args:
        logger_name: The name of logger.

    Returns:
        Logger reformatted for this package.
    """
    ...

def get_cash_root_path(version: str) -> Path:
    """Return the cash root dir path."""
    ...

def get_qdarktheme_root_path() -> Path:
    """Return the qdarktheme package root path.

    Returns:
        qdarktheme package root path.
    """
    ...

def analyze_version_str(target_version: str, version_text: str) -> bool:
    """Analyze text comparing versions."""
    ...
