"""
This type stub file was generated by pyright.
"""

from qtpy import QtWidgets

class _PropertiesDelegate(QtWidgets.QStyledItemDelegate):
    def paint(self, painter, option, index):  # -> None:
        """
        Args:
            painter (QtGui.QPainter):
            option (QtGui.QStyleOptionViewItem):
            index (QtCore.QModelIndex):
        """
        ...

class _PropertiesList(QtWidgets.QTableWidget):
    def __init__(self, parent=...) -> None: ...
    def wheelEvent(self, event):  # -> None:
        """
        Args:
            event (QtGui.QWheelEvent):
        """
        ...

class _PropertiesContainer(QtWidgets.QWidget):
    """
    Node properties container widget that displays nodes properties under
    a tab in the ``NodePropWidget`` widget.
    """

    def __init__(self, parent=...) -> None: ...
    def __repr__(self):  # -> str:
        ...

    def add_widget(self, name, widget, value, label=..., tooltip=...):  # -> None:
        """
        Add a property widget to the window.

        Args:
            name (str): property name to be displayed.
            widget (BaseProperty): property widget.
            value (object): property value.
            label (str): custom label to display.
            tooltip (str): custom tooltip.
        """
        ...

    def get_widget(self, name):  # -> None:
        """
        Returns the property widget from the name.

        Args:
            name (str): property name.

        Returns:
            QtWidgets.QWidget: property widget.
        """
        ...

    def get_all_widgets(self):  # -> dict[Any, Any]:
        """
        Returns the node property widgets.

        Returns:
            dict: {name: widget}
        """
        ...

class _PortConnectionsContainer(QtWidgets.QWidget):
    """
    Port connection container widget that displays node ports and connections
    under a tab in the ``NodePropWidget`` widget.
    """

    def __init__(self, parent=..., node=...) -> None: ...
    def __repr__(self):  # -> str:
        ...

    def set_lock_controls_disable(self, disable=...):  # -> None:
        """
        Enable/Disable port lock column widgets.

        Args:
            disable (bool): true to disable checkbox.
        """
        ...

class NodePropEditorWidget(QtWidgets.QWidget):
    """
    Node properties editor widget for display a Node object.

    Args:
        parent (QtWidgets.QWidget): parent object.
        node (NodeGraphQt.NodeObject): node.
    """

    property_changed = ...
    property_closed = ...
    def __init__(self, parent=..., node=...) -> None: ...
    def __repr__(self):  # -> str:
        ...

    def node_id(self):
        """
        Returns the node id linked to the widget.

        Returns:
            str: node id
        """
        ...

    def add_widget(self, name, widget, tab=...):  # -> None:
        """
        add new node property widget.

        Args:
            name (str): property name.
            widget (BaseProperty): property widget.
            tab (str): tab name.
        """
        ...

    def add_tab(self, name):
        """
        add a new tab.

        Args:
            name (str): tab name.

        Returns:
            PropListWidget: tab child widget.
        """
        ...

    def get_tab_widget(self):  # -> QTabWidget:
        """
        Returns the underlying tab widget.

        Returns:
            QtWidgets.QTabWidget: tab widget.
        """
        ...

    def get_widget(self, name):  # -> PropLineEdit | None:
        """
        get property widget.

        Args:
            name (str): property name.

        Returns:
            NodeGraphQt.custom_widgets.properties_bin.prop_widgets_abstract.BaseProperty: property widget.
        """
        ...

    def get_all_property_widgets(self):  # -> list[PropLineEdit]:
        """
        get all the node property widgets.

        Returns:
            list[BaseProperty]: property widgets.
        """
        ...

    def get_port_connection_widget(self):  # -> _PortConnectionsContainer | None:
        """
        Returns the ports connections container widget.

        Returns:
            _PortConnectionsContainer: port container widget.
        """
        ...

    def set_port_lock_widgets_disabled(self, disabled=...):  # -> None:
        """
        Enable/Disable port lock column widgets.

        Args:
            disabled (bool): true to disable checkbox.
        """
        ...

class PropertiesBinWidget(QtWidgets.QWidget):
    """
    The :class:`NodeGraphQt.PropertiesBinWidget` is a list widget for displaying
    and editing a nodes properties.

    .. inheritance-diagram:: NodeGraphQt.PropertiesBinWidget
        :parts: 1

    .. image:: ../_images/prop_bin.png
        :width: 950px

    .. code-block:: python
        :linenos:

        from NodeGraphQt import NodeGraph, PropertiesBinWidget

        # create node graph.
        graph = NodeGraph()

        # create properties bin widget.
        properties_bin = PropertiesBinWidget(parent=None, node_graph=graph)
        properties_bin.show()

    See Also:
            :meth:`NodeGraphQt.BaseNode.add_custom_widget`,
            :meth:`NodeGraphQt.NodeObject.create_property`,
            :attr:`NodeGraphQt.constants.NodePropWidgetEnum`

    Args:
        parent (QtWidgets.QWidget): parent of the new widget.
        node_graph (NodeGraphQt.NodeGraph): node graph.
    """

    property_changed = ...
    def __init__(self, parent=..., node_graph=...) -> None: ...
    def __repr__(self):  # -> str:
        ...

    def create_property_editor(self, node):  # -> NodePropEditorWidget:
        """
        Creates a new property editor widget from the provided node.

        (re-implement for displaying custom node property editor widget.)

        Args:
            node (NodeGraphQt.NodeObject): node object.

        Returns:
            NodePropEditorWidget: property editor widget.
        """
        ...

    def limit(self):  # -> int:
        """
        Returns the limit for how many nodes can be loaded into the bin.

        Returns:
            int: node limit.
        """
        ...

    def set_limit(self, limit):  # -> None:
        """
        Set limit of nodes to display.

        Args:
            limit (int): node limit.
        """
        ...

    def add_node(self, node):  # -> None:
        """
        Add node to the properties bin.

        Args:
            node (NodeGraphQt.NodeObject): node object.
        """
        ...

    def remove_node(self, node):  # -> None:
        """
        Remove node from the properties bin.

        Args:
            node (str or NodeGraphQt.BaseNode): node id or node object.
        """
        ...

    def lock_bin(self):  # -> None:
        """
        Lock/UnLock the properties bin.
        """
        ...

    def clear_bin(self):  # -> None:
        """
        Clear the properties bin.
        """
        ...

    def get_property_editor_widget(self, node):  # -> QWidget | None:
        """
        Returns the node property editor widget.

        Args:
            node (str or NodeGraphQt.NodeObject): node id or node object.

        Returns:
            NodePropEditorWidget: node property editor widget.
        """
        ...
