"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from qdarktheme.qtpy.qt_compat import QT_API
from PySide6.QtWidgets import *
from PyQt6.QtWidgets import *

"""Module for QtWidgets."""
if QT_API == "PySide6":
    ...
else:
    ...

class Application(QApplication):
    """Override QApplication."""

    def __init__(self, args: Sequence[str] | None = ...) -> None:
        """Override QApplication method."""
        ...

    def exec(self) -> int:
        """Override QApplication method."""
        ...

    def exit(self, returnCode: int = ...) -> None:
        """Override QApplication method."""
        ...

QApplication = ...
