"""
This type stub file was generated by pyright.
"""

from os import PathLike
from pathlib import Path
from typing import Union

PathOrStr = Union[str, PathLike[str]]
CACHE_DIRECTORY: PathOrStr = ...

def set_cache_dir(cache_dir: PathOrStr) -> None:
    """
    Set the global default cache directory.
    """
    ...

def get_cache_dir() -> Path:
    """
    Get the global default cache directory.
    """
    ...
