"""
This type stub file was generated by pyright.
"""

class NodeGraphMenu:
    """
    The ``NodeGraphMenu`` is the main context menu triggered from the node graph.

    .. inheritance-diagram:: NodeGraphQt.NodeGraphMenu
        :parts: 1

    example for accessing the node graph context menu.

    .. code-block:: python
        :linenos:

        from NodeGraphQt import NodeGraph

        node_graph = NodeGraph()

        # get the context menu for the node graph.
        context_menu = node_graph.get_context_menu('graph')

    """

    def __init__(self, graph, qmenu) -> None: ...
    def __repr__(self):  # -> str:
        ...

    @property
    def qmenu(self):  # -> Any:
        """
        The underlying QMenu.

        Returns:
            BaseMenu: menu object.
        """
        ...

    def name(self):
        """
        Returns the name for the menu.

        Returns:
            str: label name.
        """
        ...

    def get_items(self):  # -> list[Any]:
        """
        Return the menu items in the order they were added.

        Returns:
            list: current menu items.
        """
        ...

    def get_menu(self, name):  # -> None:
        """
        Returns the child menu by name.

        Args:
            name (str): name of the menu.

        Returns:
            NodeGraphQt.NodeGraphMenu: menu item.
        """
        ...

    def get_command(self, name):  # -> None:
        """
        Returns the child menu command by name.

        Args:
            name (str): name of the command.

        Returns:
            NodeGraphQt.NodeGraphCommand: context menu command.
        """
        ...

    def add_menu(self, name):  # -> NodeGraphMenu:
        """
        Adds a child menu to the current menu.

        Args:
            name (str): menu name.

        Returns:
            NodeGraphQt.NodeGraphMenu: the appended menu item.
        """
        ...

    def add_command(self, name, func=..., shortcut=...):  # -> NodeGraphCommand:
        """
        Adds a command to the menu.

        Args:
            name (str): command name.
            func (function): command function eg. "func(``graph``)".
            shortcut (str): shortcut key.

        Returns:
            NodeGraphQt.NodeGraphCommand: the appended command.
        """
        ...

    def add_separator(self):  # -> None:
        """
        Adds a separator to the menu.
        """
        ...

class NodesMenu(NodeGraphMenu):
    """
    The ``NodesMenu`` is the context menu triggered from a node.

    .. inheritance-diagram:: NodeGraphQt.NodesMenu
        :parts: 1

    example for accessing the nodes context menu.

    .. code-block:: python
        :linenos:

        from NodeGraphQt import NodeGraph

        node_graph = NodeGraph()

        # get the nodes context menu.
        nodes_menu = node_graph.get_context_menu('nodes')
    """

    def add_command(
        self, name, func=..., node_type=..., node_class=..., shortcut=...
    ):  # -> NodeGraphCommand:
        """
        Re-implemented to add a command to the specified node type menu.

        Args:
            name (str): command name.
            func (function): command function eg. "func(``graph``, ``node``)".
            node_type (str): specified node type for the command.
            node_class (class): specified node class for the command.
            shortcut (str): shortcut key.

        Returns:
            NodeGraphQt.NodeGraphCommand: the appended command.
        """
        ...

class NodeGraphCommand:
    """
    Node graph menu command.

    .. inheritance-diagram:: NodeGraphQt.NodeGraphCommand
        :parts: 1

    """

    def __init__(self, graph, qaction, func=...) -> None: ...
    def __repr__(self):  # -> str:
        ...

    @property
    def qaction(self):  # -> Any:
        """
        The underlying qaction.

        Returns:
            GraphAction: qaction object.
        """
        ...

    @property
    def slot_function(self):  # -> None:
        """
        The function executed by this command.

        Returns:
            function: command function.
        """
        ...

    def name(self):
        """
        Returns the name for the menu command.

        Returns:
            str: label name.
        """
        ...

    def set_shortcut(self, shortcut=...):  # -> None:
        """
        Sets the shortcut key combination for the menu command.

        Args:
            shortcut (str): shortcut key.
        """
        ...

    def run_command(self):  # -> None:
        """
        execute the menu command.
        """
        ...

    def set_enabled(self, state):  # -> None:
        """
        Sets the command to either be enabled or disabled.

        Args:
            state (bool): true to enable.
        """
        ...

    def set_hidden(self, hidden):  # -> None:
        """
        Sets then command item visibility in the context menu.

        Args:
            hidden (bool): true to hide the command item.
        """
        ...

    def show(self):  # -> None:
        """
        Set the command to be visible in the context menu.
        """
        ...

    def hide(self):  # -> None:
        """
        Set the command to be hidden in the context menu.
        """
        ...
