"""
This type stub file was generated by pyright.
"""

from __future__ import annotations

from NodeGraphQt.base.model import PortModel
from NodeGraphQt.nodes.base_node import BaseNode

class Port:
    """
    The ``Port`` class is used for connecting one node to another.

    .. inheritance-diagram:: NodeGraphQt.Port

    .. image:: _images/port.png
        :width: 50%

    See Also:
        For adding a ports into a node see:
        :meth:`BaseNode.add_input`, :meth:`BaseNode.add_output`

    Args:
        node (NodeGraphQt.NodeObject): parent node.
        port (PortItem): graphic item used for drawing.
    """

    def __init__(self, node, port) -> None: ...
    def __repr__(self):  # -> str:
        ...

    @property
    def view(self):  # -> Any:
        """
        Returns the :class:`QtWidgets.QGraphicsItem` used in the scene.

        Returns:
            NodeGraphQt.qgraphics.port.PortItem: port item.
        """
        ...

    @property
    def model(self) -> PortModel:
        """
        Returns the port model.

        Returns:
            NodeGraphQt.base.model.PortModel: port model.
        """
        ...

    def type_(self) -> str:
        """
        Returns the port type.

        Port Types:
            - :attr:`NodeGraphQt.constants.IN_PORT` for input port
            - :attr:`NodeGraphQt.constants.OUT_PORT` for output port

        Returns:
            str: port connection type.
        """
        ...

    def multi_connection(self) -> bool:
        """
        Returns if the ports is a single connection or not.

        Returns:
            bool: false if port is a single connection port
        """
        ...

    def node(self) -> BaseNode:
        """
        Return the parent node.

        Returns:
            NodeGraphQt.BaseNode: parent node object.
        """
        ...

    def name(self) -> str:
        """
        Returns the port name.

        Returns:
            str: port name.
        """
        ...

    def visible(self) -> bool:
        """
        Port visible in the node graph.

        Returns:
            bool: true if visible.
        """
        ...

    def set_visible(self, visible=..., push_undo=...):  # -> None:
        """
        Sets weather the port should be visible or not.

        Args:
            visible (bool): true if visible.
            push_undo (bool): register the command to the undo stack. (default: True)
        """
        ...

    def locked(self):  # -> bool:
        """
        Returns the locked state.

        If ports are locked then new pipe connections can't be connected
        and current connected pipes can't be disconnected.

        Returns:
            bool: true if locked.
        """
        ...

    def lock(self):  # -> None:
        """
        Lock the port so new pipe connections can't be connected and
        current connected pipes can't be disconnected.

        This is the same as calling :meth:`Port.set_locked` with the arg
        set to ``True``
        """
        ...

    def unlock(self):  # -> None:
        """
        Unlock the port so new pipe connections can be connected and
        existing connected pipes can be disconnected.

        This is the same as calling :meth:`Port.set_locked` with the arg
        set to ``False``
        """
        ...

    def set_locked(
        self, state: bool = ..., connected_ports: bool = ..., push_undo: bool = ...
    ) -> None:
        """
        Sets the port locked state. When locked pipe connections can't be
        connected or disconnected from this port.

        Args:
            state (Bool): port lock state.
            connected_ports (Bool): apply to lock state to connected ports.
            push_undo (bool): register the command to the undo stack. (default: True)
        """
        ...

    def connected_ports(self) -> list[Port]:
        """
        Returns all connected ports.

        Returns:
            list[NodeGraphQt.Port]: list of connected ports.
        """
        ...

    def connect_to(self, port=..., push_undo=..., emit_signal=...):
        """
        Create connection to the specified port and emits the
        :attr:`NodeGraph.port_connected` signal from the parent node graph.

        Args:
            port (NodeGraphQt.Port): port object.
            push_undo (bool): register the command to the undo stack. (default: True)
            emit_signal (bool): emit the port connection signals. (default: True)
        """
        ...

    def disconnect_from(self, port=..., push_undo=..., emit_signal=...):  # -> None:
        """
        Disconnect from the specified port and emits the
        :attr:`NodeGraph.port_disconnected` signal from the parent node graph.

        Args:
            port (NodeGraphQt.Port): port object.
            push_undo (bool): register the command to the undo stack. (default: True)
            emit_signal (bool): emit the port connection signals. (default: True)
        """
        ...

    def clear_connections(self, push_undo=..., emit_signal=...):  # -> None:
        """
        Disconnect from all port connections and emit the
        :attr:`NodeGraph.port_disconnected` signals from the node graph.

        See Also:
            :meth:`Port.disconnect_from`,
            :meth:`Port.connect_to`,
            :meth:`Port.connected_ports`

        Args:
            push_undo (bool): register the command to the undo stack. (default: True)
            emit_signal (bool): emit the port connection signals. (default: True)
        """
        ...

    def add_accept_port_type(self, port_name, port_type, node_type):  # -> None:
        """
        Add a constraint to "accept" a pipe connection.

        Once a constraint has been added only ports of that type specified will
        be allowed a pipe connection.

        `Implemented in` ``v0.6.0``

        See Also:
            :meth:`NodeGraphQt.Port.add_reject_ports_type`,
            :meth:`NodeGraphQt.BaseNode.add_accept_port_type`

        Args:
            port_name (str): name of the port.
            port_type (str): port type.
            node_type (str): port node type.
        """
        ...

    def accepted_port_types(self):
        """
        Returns a dictionary of connection constrains of the port types
        that allow for a pipe connection to this node.

        See Also:
            :meth:`NodeGraphQt.BaseNode.accepted_port_types`

        Returns:
            dict: {<node_type>: {<port_type>: [<port_name>]}}
        """
        ...

    def add_reject_port_type(self, port_name, port_type, node_type):  # -> None:
        """
        Add a constraint to "reject" a pipe connection.

        Once a constraint has been added only ports of that type specified will
        be rejected a pipe connection.

        `Implemented in` ``v0.6.0``

        See Also:
            :meth:`NodeGraphQt.Port.add_accept_ports_type`,
            :meth:`NodeGraphQt.BaseNode.add_reject_port_type`

        Args:
            port_name (str): name of the port.
            port_type (str): port type.
            node_type (str): port node type.
        """
        ...

    def rejected_port_types(self):
        """
        Returns a dictionary of connection constrains of the port types
        that are NOT allowed for a pipe connection to this node.

        See Also:
            :meth:`NodeGraphQt.BaseNode.rejected_port_types`

        Returns:
            dict: {<node_type>: {<port_type>: [<port_name>]}}
        """
        ...

    @property
    def color(self): ...
    @color.setter
    def color(self, color=...):  # -> None:
        ...

    @property
    def border_color(self): ...
    @border_color.setter
    def border_color(self, color=...):  # -> None:
        ...
