"""
This type stub file was generated by pyright.
"""

from qdarktheme._resources import colors, palette, stylesheets, svg

"""Package including resources.

**Warning**

This package created programmatically. All changes made in this file will be lost!
Created by the `PyQtDarkTheme/tools/build_styles`.

"""
THEMES = ...
