"""
This type stub file was generated by pyright.
"""

from functools import partial
from qdarktheme._template.engine import Template

"""Module loading QPalette."""

def q_palette(
    mk_template: partial[Template],
    color_map: dict[str, str | dict],
    for_stylesheet: bool,
):  # -> QPalette:
    """Generate QPalette."""
    ...
