"""
This type stub file was generated by pyright.
"""

from qdarktheme.qtpy.QtCore import QEvent, QObject, QThread

class OSThemeSwitchListener(QThread):
    """Listener to detect to change OS's theme."""

    sig_run = ...
    _sig_listen_os_theme = ...
    def __init__(self, callable) -> None:
        """Initialize listener."""
        ...

    def eventFilter(self, q_object: QObject, event: QEvent) -> bool:
        """Override QObject.eventFilter.

        This override is for Mac.
        Qt can listen to change OS's theme on only mac and changed QPalette automatically.
        So enable to listen to change OS's theme via palette change event.
        """
        ...

    def run(self) -> None:
        """Override QThread.run.

        This override is for except Mac.
        Qt cannot listen to change OS's theme on except Mac.
        Use ``darkdetect.listener`` to detect to change OS's theme.
        """
        ...

    def kill(self) -> None:
        """Kill thread."""
        ...
