"""
This type stub file was generated by pyright.
"""

from qdarktheme._icon.svg import Svg
from qdarktheme.qtpy.QtCore import QRect, QSize
from qdarktheme.qtpy.QtGui import QIcon, QIconEngine, QPainter

class SvgIconEngine(QIconEngine):
    """A custom QIconEngine that can render an SVG buffer."""

    def __init__(self, svg: Svg) -> None:
        """Initialize icon engine."""
        ...

    def paint(
        self, painter: QPainter, rect: QRect, mode: QIcon.Mode, state
    ):  # -> None:
        """Paint the icon int ``rect`` using ``painter``."""
        ...

    def clone(self):  # -> SvgIconEngine:
        """Required to subclass abstract QIconEngine."""
        ...

    def pixmap(self, size: QSize, mode: QIcon.Mode, state: QIcon.State):  # -> QPixmap:
        """Return the icon as a pixmap with requested size, mode, and state."""
        ...
