"""
This type stub file was generated by pyright.
"""

from qdarktheme._color import Color

class Svg:
    """Class to manage SVG."""

    _SVG_FILL_RE = ...
    _SVG_FILL_OPACITY_RE = ...
    _SVG_TRANSFORM_RE = ...
    def __init__(self, id: str) -> None:
        """Initialize svg manager."""
        ...

    def __str__(self) -> str:
        """Return the svg source code."""
        ...

    def colored(self, color: Color) -> Svg:
        """Add or change svg color."""
        ...

    def rotate(self, rotate: int) -> Svg:
        """Rotate svg."""
        ...
